version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - OPC_SERVER_URL=opc.tcp://opc-server:4840/freeopcua/server/
      - DEV_MODE=true

    depends_on:
      - opc-server

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000/api
    command: sh -c "npm install && npm start"
    depends_on:
      - backend

  opc-server:
    build:
      context: ./opc_server
      dockerfile: Dockerfile.dev
    volumes:
      - ./opc_server:/app

    ports:
      - "4840:4840"
